trigger:
- master

pool:
  vmImage: 'windows-latest'
 
jobs:

- job: 'Build'

  displayName: 'Build the application'

  steps:

  - script: 'dotnet build --configuration Release'

    displayName: 'Build the project'

 

- job: 'Deploy'

  displayName: 'Deploy to Azure App Service'

  environment: 'your-environment'

  dependsOn: 'Build'

  steps:

  - script: 'az webapp deployment zip --resource-group your-resource-group --name your-app-name --src $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'

    displayName: 'Deploy the application'